name: Build
on: [push, pull_request]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for ${{ matrix.abi }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-global-

      - name: Cache Buildozer local build
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: buildozer-local-${{ matrix.abi }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-local-${{ matrix.abi }}-

      - name: Set ABI in buildozer.spec
        run: |
          sed -i 's/android.arch = .*/android.arch = ${{ matrix.abi }}/' buildozer.spec

      - name: Get short Git commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Replace hash and update channel in config.py
        run: |
          sed -i 's/HASH = ".*"/HASH = "'$COMMIT_HASH'"/' config.py
          sed -i 's/UPDATE_CHANNEL = ".*"/UPDATE_CHANNEL = "nightly"/' config.py

      - name: Clean bin directory
        run: rm -rf bin/*

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      - name: Fix Permission 
        run: |
          sudo chmod -R 777 bin/

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2
          target: android-33
          ndk: 25.2.9519653

      - name: Install build-tools 29.0.3
        run: yes | sdkmanager "build-tools;29.0.3"

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: bin/
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}

      - uses: actions/upload-artifact@v4
        with:
          name: FrogCard-${{ matrix.abi }}-signed
          path: ${{steps.sign_app.outputs.signedReleaseFile}}