name: Release Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
      release_name:
        description: 'Release name (e.g. FrogCard v1.0.0)'
        required: true
      release_body:
        description: 'Release description'
        required: false
        default: ''

jobs:
  build-android-release:
    name: Build Android Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}
        
      - name: Get short Git commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Replace version and update channel in config.py
        run: |
          sed -i 's/APP_VERSION = ".*"/APP_VERSION = "${{ github.event.inputs.release_tag }}"/' config.py
          sed -i 's/UPDATE_CHANNEL = ".*"/UPDATE_CHANNEL = "release"/' config.py
          sed -i 's/HASH = ".*"/HASH = "$HASH"/' config.py

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      - name: Fix Permission 
        run: sudo chmod -R 777 bin/

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2
          target: android-33
          ndk: 25.2.9519653

      - name: Install build-tools 29.0.3
        run: yes | sdkmanager "build-tools;29.0.3"

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: bin/
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload to GitHub Release (draft)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_body }}
          draft: true
          files: ${{ steps.sign_app.outputs.signedReleaseFile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
